import os
from pathlib import Path

# === CONFIGURACIÓN ===
RAW_DATA_DIR = "notebooks/data/raw"  # Carpeta donde están los .pgn
OUTPUT_FILE = "users.txt"            # Archivo de salida con los pendientes

# Tu lista completa de jugadores (debe estar definida antes de ejecutar este script)
# Ejemplo:

# Lista de jugadores (ejemplo con algunos, puedes extenderla)
USERNAMES = [
    # === Títulos y patrocinados originales ===
    "VladimirSakun",        # FM
    "ajkumar",              # FM
    "stefan_95",            # FM
    "killer311",            # FM
    "BeStRoMaNo",           # NM
    "EmmanuelJimenez",      # IM
    "Mistheoretical",       # CM
    "ChessyClub",           # WNM
    "steva23",              # FM
    "lokiy47",              # IM

    # === Top 200 Clásica (parcial, ya que muchos se repiten) ===
    "yuuki-asuna",
    "XII_MARSHAL",
    "Vlad_Lazarev79",
    "Truemasterme",
    "Lucon2000",
    "platinumcrown",
    "matteorf2b",
    "MW1966",
    "CoD_Dragon",
    "antonpraim",
    "tommy_pug",
    "ChessTheory64",
    "Konnov_Oleg",
    "Unstoppable_Rob",
    "avcs",
    "OjaiJoao",
    "Thorwald5",
    "White_Robot",
    "SergeiRK",
    "Underdelo",
    "Art-Vega",
    "StarKid20",
    "DAVIDmark",
    "Fasmc17",
    "Yorkster",
    "Victory_Biber",
    "PREDATOR624",
    "BlackMist2025",
    "gek76",
    "trenersahnutyi",
    "AsacoPaco",
    "RE-BORN",
    "neelunani5",
    "Giobra",
    "m_t_h",
    "iCe_eNerGyTeaM",
    "ChessClubKomotini",
    "daaleksandrov",
    "Felicity187",
    "uzkuzk",
    "Anton_Maximov",
    "Padurean_Daniel",
    "EldarMv",
    "FlyingLemon",
    "nilete",
    "silent-killer2265",
    "shaheus",
    "Tictoocchess",
    "faznaz83",
    "Abyin2000",
    "TiberianDawn",
    "Bauernschach24",
    "kqchess14anirudhs",
    "Shasi12345",
    "Alen555",
    "Cris2016",
    "Stallion28",
    "Nosporchess",
    "AlexHas22",
    "CryptoPanda",
    "Chess_for_some",
    "artistendo",
    "Alex1-Victory20",
    "Schachstratege",
    "Nobita2345678",
    "Imangalikhafiz",
    "pavaobjazevic",
    "AA2017",
    "Vadim0507001012",
    "MintRefreshments",
    "the-chess-uni",
    "grrrrrrr_r",
    "Delebarre",
    "Kawaciukov",
    "Befidemaster",
    "bkamber",
    "vasudev9",
    "Aleks-lexa",
    "Artem_3000",
    "GANESHGD",
    "Ema_Roma87",
    "JaremaC00l",
    "drudim",
    "DmitriyNagiev",
    "aleatorio00",
    "OnlyVariantMaster_qX",
    "minhnm2020",
    "Fingolfin69",
    "AOTxLeviAckerman",
    "Alex_Chi",
    "Hulscher_1979",
    "whenrooksfly",
    "loristavernier",
    "Rajibmr",
    "bulgakov1967",
    "Lyubatheonlyone",
    "Hematom87",
    "sidfanDX",
    "Viktor_Tahirov555",
    "pal22",
    "tavli",
    "WangMuyuan123",
    "Aldmuo",
    "SashaLemish",
    "Simchev",
    "Bhavya33",
    "UrNotHimGetOut123",
    "miwi2",
    "Xicxoc",
    "sheep1965",
    "mkenenisa",
    "Silkthewanderer",
    "nimzo5",
    "BlindJagulep",
    "yoyo-liu",
    "Joejan",
    "YSPchess",
    "PawnEatingZombie",
    "Fatcatsat",
    "ferenclist",
    "Salomon_V",
    "ChessInsomniac",
    "jessehf",
    "Just_The-King2011",
    "STAR_ARYA",
    "Bida1992",
    "Avslugin80",
    "JanHextall",
    "LeRusher",
    "tanu14",
    "familychess1",
    "IRFANHARITHROSLI",
    "chesstrial2013",
    "pouyaaa",
    "gmshloky",
    "WILDMOUNTAIN2020",
    "rockon_123",
    "Nitrogue",
    "Henryshen2024",
    "ConwyCastle",
    "CANDIDATEMASTER99999",
    "wizard1983",

    # === Top 200 Rápida (rapid) ===
    "Pap-G",
    "ilqar_7474",
    "Rakhmanov_Aleksandr",
    "Kurald_Galain",
    "Tuzakli_Egitim",
    "Sharkfang",
    "Arteler",
    "chessmem",
    "Aristarch_Kukuev",
    "MatthewG-p4p",
    "einstein_79",
    "Cf3paraCg1",
    "byebob",
    "Matinghffarifar",
    "Svuezoz",
    "LittlePumpkin",
    "chessmount",
    "Frankeinsteinzombie",
    "sotirakis",
    "Andrey11976",
    "Prettyfishy",
    "snakeice",
    "bearhardy",
    "NorthWind05",
    "Herobrine_Undefeated",
    "OpeningScientist",
    "ChessGenius-Alphazeo",
    "shidfar2007",
    "Hossein_MZ",
    "AllGunsBlazing22",
    "Anonimous-1981",
    "Paxavarica",
    "A-X-L",
    "interestinglandscape",
    "LavishChess",
    "NedamReddam",
    "Mazen_Ahmed2008",
    "CHESS_Toxik",
    "AnIndianChessplayer",
    "Akshak",
    "QuCaNi",
    "OX528354",
    "Haunting_Games",
    "Suleyman_Chess06",
    "AlexChessChamp",
    "catanalyst",
    "maksattamsat",
    "The_Supreme_Judge",
    "TheCableBox",
    "ShellingFord92",
    "AtalikS",
    "DarkNebula-B",
    "TheMagnet",
    "OwnYulix",
    "Hammurapi65",
    "happykid0000",
    "StochasticVolatility",
    "albowiem",
    "adhamyas",
    "Mr_StarrySky",
    "bullishmoves",
    "Mikevs",
    "MassterofMayhem",
    "schachinator999",
    "Breathing_water",
    "Mahlermaniaco",
    "LObbyist6",
    "ORACLEof64",
    "YaaasQueen",
    "Bandhawk",
    "love_you_one",
    "Kradstalmund",
    "Henryletennisman26",
    "Postnova_Margarita12",
    "tireDemocrat",
    "lorenfer",
    "Volga_Tiger",
    "C01B01",
    "IgnatevDP",
    "Qcfxi_dizsdicx",
    "Larrythecabledude",
    "KrsnArjun",
    "newaccwhothis",
    "daddystrength",
    "Max05",
    "C0mB1n0v1tch",
    "Monarch2023",
    "SergeyNadeev",
    "Estonicca",
    "edziomobil",
    "Amin_NH",
    "Jossbros",
    "bagera9",
    "rehbwf",
    "Knight_ofthelight73",
    "Kysylyn",
    "FianuioAspas12",
    "Kodrut",
    "Roman2001",
    "PathtoVictory3000",
    "MATRIXTRINITY",
    "LevGLev",
    "Dynamicus",
    "Lion_King11",
    "jbking07",
    "Mind05",
    "Idvan",
    "MasteringHW",
    "JB2906",
    "QLS-Xagavan",
    "joeALT30",
    "mr-a7aaaa17a7a",
    "Crichero2024",
    "WYshishabi",
    "BudiRizkiansyah",
    "ArieWerksma",
    "HamedManoochehri",
    "Tiamo_Firenze",
    "TheDestinedOne",
    "JesusChristConquers",
    "Weerasekara",
    "nmiq",
    "Super_BrainPower",
    "MarkosianDavid",
    "Nidmas",
    "dkodwkc",
    "AliAyman127",
    "b31b6Consultant",
    "BlindMonster",
    "littleprince1981",
    "tramvay",
    "zanycolourfulwindow",
    "Jai_Gurudev",
    "Atomrod",
    "AntiberserkM",
    "Heisenberg9115",
    "HandKnit",
    "Stephen31",
    "OnlyRapid11",
    "Quorvex",
    "lada23new",
    "Smash_01",
    "buldym",
    "Bennerbeatbox",
    "Victorterror1",
    "I_WANT_MORE",
    "komodo54",
    "Grempsi",
    "i_love_1C",
    "d-pawn",
    "froggykermit",
    "FrozenWords",
    "RubinsteinsMonster",
    "putpressureonapinned",
    "bobmarley1love",
    "andy2342",
    "Aviamotornaya",
    "Odette_de_Crecy",
    "Proward05",
    "brawlball",
    "nikolarasss",
    "Jspace02",
    "Zombieblitz",
    "sabke",
    "CoachCai",
    "STN_Chess",
    "Daddy_economics",
    "Prepstoring",
    "CzechWarrior",
    "Suhov549",
    "Sameh2023",
    "d1rector",
    "mystisking",
    "ppom12",
    "JJPlayz",
    "JG2001",
    "HoMeEeEr",
    "Magnus_misr",
    "Debagg",
    "h5h6h7",
    "Nikita272005",
    "autko46",
    "PinkWafflePig",
    "BeatrizRuvieri",
    "powerking96",
    "extermo44",
    "FlyyElloW_2000YO",
    "Aleph_Vox",
    "bosspotato",
    "a_boring_username",
    "Tharvin2010",
    "andreu666",
    "Opening_Master9",
    "Aichyy",
]
BLITZ_TOP_200 = [
    "Dr_Tiger",
    "Sportik_Shark",
    "Fran4477",
    "Yarebore",
    "cutemouse83",
    "teem1",
    "FeelingLiberated",
    "athena-pallada",
    "delta_horsey",
    "Schachmachine",
    "InvisibleGuest2023",
    "Tuzakli_Egitim",  # Ya estaba en rapid, pero muy fuerte
    "Mr_BaronMunchausen",
    "TigerSiberian",
    "Ilikeknightmost",
    "lqevsll",
    "Tintirito",
    "Ciderdrinker",
    "Arjun2002",
    "BrittaBagels",
    "ilqar_7474",  # Muy fuerte en múltiples formatos
    "elconceto",
    "NeverEnough",
    "Tsoi_Dima",
    "AVS2000",
    "ChessLab_Online",
    "Lintchevski_Daniil",
    "Batko2003",
    "Amateur_IM",
    "BackToJune",
    "Hotprimus",
    "vistagausta",
    "RealDavidNavara",
    "MatthewG-p4p",  # Ya en otras listas
    "am31",
    "LoveFifi",
    "Juan_Delasala",
    "Lu_Shanglei",
    "Secret_Spion",
    "FeegLood",
    "Lukianoo",
    "Mlchael",
    "evg85",
    "Bllitzer11",
    "KAPUTVSEMU",
    "MJRFRNLM",
    "Freestyler1999",
    "hideseeker",
    "QuarterPawn",
    "vistagusta",  # Duplicado con vistagausta, corregido
    "arturchix",
    "gmmoranda",
    "LeelooKorbenDallas",
    "lovely_fella",
    "Chewbacca18",
    "flower9503",
    "pozvonochek",
    "nrvisakh",
    "BenjaminBokTwitch",
    "platinumcrown",  # Ya en otras listas
    "IVK88",
    "EvilGenius94",
    "gefuehlter_FM",
    "DiaryTraining",
    "raf1310",
    "Bamboccione",
    "Zangyglobal",
    "TarmosanCheese",
    "WhiteRabbit00735",
    "MikeGScarn",
    "Jakebr8",
    "chessed70",
    "vaynebot",
    "AlexTriapishko",
    "DeutcheArtist3000",
    "BrightFalcon",
    "Solidifying",
    "cjota95",
    "Buhmann",
    "Azzir",
    "DrawDenied_Twitch",
    "SF-46",
    "Shpittsik",
    "Xmaskerino_Student",
    "NINDJAxx8",
    "bishop1984",
    "Christened",
    "TacticsMan23",
    "Elda64",
    "Cann_Karo",
    "Cruise97",
    "MOTAR0",
    "Dragso",
    "Iron_Man1703",
    "chesswithmra",
    "BrokyLoveKFC",
    "Rakhmanov_Aleksandr",  # Fuerte en todas partes
    "GK1963",
    "K-Georgiev",
    "ixci",
    "ReluctantCannibal",
    "anonymousblitz",
    "temus22",
    "paniculata",
    "BENED7707",
    "woshigeshagua",
    "DingLiren7777777",
    "Samid2002",
    "Nana_jede_cevape",
    "Heisenberg01",
    "bulletnik",
    "Hanskai",
    "TryhardTrainingTiger",
    "Unbroken_Warrior",
    "Coach13",
    "Andrey11976",  # Repetido, pero relevante
    "jake_jortles",
    "Popovich2020",
    "abudabi22840",
    "BatmanBinSuperman",
    "dr_XXL",
    "Baidetskyi_Valentin",
    "horsebishop123",
    "Conan_The_Barbarian8",
    "Chesstoday",
    "Sigma_Tauri",
    "Pyama_Ninja",
    "FBINC",
    "Dr-CRO",
    "Ignathor",
    "Chariteawithambition",
    "PauArk",
    "artem64",
    "Sobino106",
    "Vostanin",
    "karagioules",
    "Fabsid",
    "forgiants",
    "Molt7n",
    "MrTactic2008",
    "TBold3",
    "gan06",
    "mzh1995",
    "Epoch11",
    "Alpha_777",
    "hansi_flick",
    "vodanou01",
    "Mikhailov_Viacheslav",
    "Jamorris94",
    "Nefer-Pitou",
    "FishhingForFish",
    "efourwhitewins",
    "IgorKowalski",
    "Train_account",
    "AnIndianChessplayer",  # Ya en otras listas
    "LeNoobsInLeTactics",
    "hristiyan06",
    "abrakadabra02",
    "Pavel-Vorontsov",
    "Sergeiaza",
    "FastforYou",
    "Woland87",
    "rasulovvugar",
    "Brokeno_smekla",
    "onepoundrook",
    "Finite_Incantatem777",
    "enmQ",
    "ReynaMatias",
    "Jumangee",
    "Lyonbeast21",
    "Kinryln",
    "tjychess",
    "AttackingBeast",
    "CrazySage",
    "Koshulyan_Egor",
    "stairsarecool",
    "DarkAlekhine",
    "Art_Vandelay1998",
    "Alexandr_KhleBovich",
    "Pblu35",
    "rfelgaer",
    "mitsutszkisszucs",
    "AASP1124",
    "kingofspeedd",
    "M24883",
    "sapphire_phoenix",
    "SavvaVetokhin2009",
    "Forester_19",
    "Carlsen_brat",
    "IsolatedMushroom",
    "paopaomate",
    "Tractor19702025",
    "Misi_95",
    "nickVet",
    "June31",
    "Yakamuzosan",
    "Biriyani",
    "okriak",
    "justantan",
    "BocchoiBoi"
]
# Combinar todas las listas sin duplicados
all_players = list(set(USERNAMES + BLITZ_TOP_200))
# === PASO 1: Obtener lista de usuarios ya descargados ===
downloaded_users = set()

# Tipos de partidas esperados
perf_types = ["bullet", "blitz", "rapid", "classical"]

# Verificar si la carpeta existe
raw_path = Path(RAW_DATA_DIR)
if not raw_path.exists():
    raise FileNotFoundError(f"La carpeta {RAW_DATA_DIR} no existe.")

# Recorrer todos los archivos .pgn
for file_path in raw_path.glob("*.pgn"):
    filename = file_path.stem  # Nombre sin extensión
    # Dividir por el último guion bajo (ej: usuario_blitz → ['usuario', 'blitz'])
    if "_" in filename:
        username = filename.rsplit("_", 1)[0].lower()
        if any(pt in filename for pt in perf_types):  # Validar que sea un tipo de partida
            downloaded_users.add(username)

print(f"🔍 Se encontraron {len(downloaded_users)} usuarios ya descargados.")

# === PASO 2: Obtener usuarios faltantes ===
# Aseguramos todo en minúsculas para comparar bien
all_players_lower = [user.strip().lower() for user in all_players]
missing_players = [user for user in all_players_lower if user not in downloaded_users]

print(f"📌 Quedan {len(missing_players)} usuarios por descargar.")

# === PASO 3: Guardar en users.txt ===
with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
    for username in missing_players:
        f.write(f"\"{username}\",\n")

print(f"✅ Archivo '{OUTPUT_FILE}' generado con éxito. Listo para usar.")